[terminal]
vt = 2

[default_session]
command = "tuigreet --time --time-format '%I:%M %p' --remember --remember-session --asterisks --theme 'border=#bd93f9;text=#f8f8f2;prompt=#50fa7b;time=#6272a4;action=#ff79c6;button=#bd93f9;container=#282a36;input=#f8f8f2' --cmd niri-session"
user = "greeter"
