monitor=WL-1,2560x1440,0x0,1

windowrulev2 = float, class:^(hearthstonedecktracker.exe)$
windowrulev2 = pin, class:^(hearthstonedecktracker.exe)$
windowrulev2 = nofocus, class:^(hearthstonedecktracker.exe)$, title:^(HearthstoneOverlay)$

windowrulev2 = float, class:^(hearthstone.exe)$
windowrulev2 = maximize, class:^(hearthstone.exe)$

windowrulev2 = float, class:^(explorer.exe)$

bind = CTRL, Return, exec, ghostty
